(()=>{
'use strict';
const DB='coaching_tracker_v3',OLD='coaching_tracker_v2',PIN='coaching_pin_v1',USER='coaching_user_name_v1',ONBOARD='coaching_onboard_v3',TARGET=100,PAID_TARGET=75;
const $=id=>document.getElementById(id),round=n=>Math.round((Number(n)||0)*100)/100,hrs=m=>round((Number(m)||0)/60),num=n=>Number.isInteger(round(n))?String(round(n)):String(round(n)),isPaid=p=>p&&p!=='免費／義務';
const fmt=d=>{if(!d)return'';let x=new Date(d+'T00:00:00');return `${x.getFullYear()}年${x.getMonth()+1}月${x.getDate()}日`};
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let mode='online',current=null,rec='沒有',tab='upcoming',last=null;
function fresh(){return{target:TARGET,paidTarget:PAID_TARGET,startingHours:0,startingPaidHours:0,items:[]}}
function load(){try{let s=JSON.parse(localStorage.getItem(DB)||'null');if(s){s.items=Array.isArray(s.items)?s.items:[];s.target=TARGET;s.paidTarget=PAID_TARGET;return{...fresh(),...s}}let o=JSON.parse(localStorage.getItem(OLD)||'null');if(o){let items=Array.isArray(o.items)?o.items:[],done=items.filter(x=>x.status==='done'),all=done.reduce((a,x)=>a+hrs(x.actual),0),paid=done.filter(x=>isPaid(x.payment)).reduce((a,x)=>a+hrs(x.actual),0);let s={...fresh(),startingHours:round((Number(o.base)||0)+all),startingPaidHours:round(paid),items:items.map(x=>x.status==='done'?{...x,countMode:'included'}:{...x})};localStorage.setItem(DB,JSON.stringify(s));return s}}catch(e){}return fresh()}
let state=load();
function save(){state.target=TARGET;state.paidTarget=PAID_TARGET;localStorage.setItem(DB,JSON.stringify(state));render()}
const done=()=>state.items.filter(x=>x.status==='done'),additive=()=>done().filter(x=>x.countMode!=='included'),total=()=>round(state.startingHours+additive().reduce((a,x)=>a+hrs(x.actual),0)),paidTotal=()=>round(state.startingPaidHours+additive().filter(x=>isPaid(x.payment)).reduce((a,x)=>a+hrs(x.actual),0)),freeTotal=()=>round(Math.max(0,total()-paidTotal())),backfilled=()=>round(done().filter(x=>x.countMode==='included').reduce((a,x)=>a+hrs(x.actual),0));
function toast(t){let x=$('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1700)}
function buildUI(){
  document.body.classList.add('v4');
  let nameField=$('nameField');if(nameField&&!$('startHours')){nameField.insertAdjacentHTML('afterend',`<div id="progressSetup"><div class="v4field"><label>目前已完成 Coaching 總時數</label><input id="startHours" type="number" inputmode="decimal" min="0" step="0.25" placeholder="例如：15"><small>填你開始使用這個 App 時，已經完成的總時數。</small></div><div class="v4field"><label>其中付費／交換時數</label><input id="startPaid" type="number" inputmode="decimal" min="0" step="0.25" placeholder="例如：10"><small>包括你自行定義為付費／交換的時數，例如互 Coach。</small></div></div>`)}
  let home=$('home');if(home)home.innerHTML=`<div class="top"><div><h1 id="welcomeName">Hi 👋</h1><p>每一節 Coaching，都在累積你的經驗與信心 💜</p></div><div class="mark">🌱</div></div><div class="hero"><div class="heroRow"><div><div class="eyebrow">⭐ ICF ACC · 100 小時</div><h2 id="heroTitle">一步一步，把經驗累積起來。</h2><p><b id="doneHours">0</b> / 100 小時<br><span id="remain"></span></p></div><div class="ring" id="ring"><div><b id="pct">0%</b><span>總進度</span></div></div></div></div><div class="v4paid"><div class="v4paidtop"><div><b>付費／交換時數</b><small>目標 75 小時</small></div><strong><span id="paidHours">0</span> / 75</strong></div><div class="progress"><span id="paidBar"></span></div><div class="v4meta"><span id="paidRemain"></span><span id="paidPct">0%</span></div></div><div class="quote" id="motivation"></div><div class="v4stats"><div><b id="freeHours">0</b><span>免費時數</span></div><div><b id="doneCount">0</b><span>已記錄節數</span></div><div><b id="upCount">0</b><span>即將進行</span></div></div><div class="v4actions"><button class="btn primary" onclick="newAppointment()">＋ 新增 Coaching 預約</button><button class="btn v4soft" onclick="newBackfill()">↶ 補錄過往 Coaching 紀錄</button></div><div class="section"><div class="sectionHead"><h3>即將進行</h3><button class="ghost" onclick="show('records')">查看全部</button></div><div id="homeList" class="list"></div></div>`;
  let records=$('records');if(records){let seg=records.querySelector('.seg');if(seg)seg.innerHTML=`<button id="upTab" class="sel" onclick="setTab('upcoming')">即將進行</button><button id="doneTab" onclick="setTab('done')">已完成／補錄</button>`;let old=records.querySelector('.btn.primary');if(old)old.outerHTML=`<div class="v4actions" style="margin-top:15px"><button class="btn primary" onclick="newAppointment()">＋ 新增 Coaching 預約</button><button class="btn v4soft" onclick="newBackfill()">↶ 補錄過往 Coaching 紀錄</button></div>`}
  if(!$('backfill')){records.insertAdjacentHTML('beforebegin',`<section id="backfill" class="screen"><div class="head"><button class="back" onclick="show('records')">‹</button><h2>補錄過往 Coaching</h2><span style="width:40px"></span></div><div class="support v4warn">🕘 <b>這是補資料，不是加時數。</b><br>這筆 Coaching 應已包含在你第一次設定的「目前已完成總時數」內，所以儲存後不會再次疊加。</div><form id="backfillForm" class="card"><div class="formSectionTitle"><span>01</span><div>過往 Coaching 資料</div></div><label>Coachee 姓名 <span class="req">*</span></label><input id="bfName" required><label>身份／職業</label><input id="bfJob"><label>聯絡電話</label><input id="bfPhone" inputmode="tel"><label>Coaching 日期 <span class="req">*</span></label><input id="bfDate" type="date" required><label>開始時間（選填）</label><input id="bfTime" type="time"><label>實際 Coaching 時長 <span class="req">*</span></label><select id="bfActual"><option value="30">30 分鐘</option><option value="45">45 分鐘</option><option value="60" selected>1 小時</option><option value="75">1 小時 15 分</option><option value="90">1.5 小時</option><option value="120">2 小時</option></select><label>進行方式</label><select id="bfMode"><option value="online">線上</option><option value="offline">面對面</option><option value="unknown">未記錄</option></select><label>地點／會議連結（選填）</label><input id="bfPlace" placeholder="例如：Zoom／中環咖啡店"><label>本節 Coaching 主題</label><textarea id="bfTopic"></textarea><div class="formSectionTitle sectionGap"><span>02</span><div>錄音與同意</div></div><label>錄音／錄影</label><select id="bfRec"><option value="沒有">沒有</option><option value="錄音">有錄音</option><option value="錄影">有錄影</option></select><label>如有錄音／錄影，對方是否已同意？</label><select id="bfConsent"><option>不適用</option><option>是</option><option>否</option></select><div class="formSectionTitle sectionGap"><span>03</span><div>Feedback 與反思</div></div><label>Coachee 的 Feedback</label><textarea id="bfFeedback"></textarea><label>你的個人反思</label><textarea id="bfReflection"></textarea><div class="formSectionTitle sectionGap"><span>04</span><div>付費／交換資料</div></div><label>付費／交換方式 <span class="req">*</span></label><select id="bfPayment"><option>互 Coach 交換</option><option>現金／轉數快</option><option>請飲咖啡</option><option>請食飯</option><option>其他實物／服務交換</option><option>免費／義務</option></select><small class="v4hint">只補回紀錄內容，不會改變你第一次輸入的付費／交換總時數。</small><label>付款／交換備註</label><input id="bfPaynote"><button class="btn primary" style="margin-top:15px" type="submit">儲存過往紀錄</button></form></section>`)}
  let stats=$('stats');if(stats)stats.innerHTML=`<div class="head"><span></span><h2>進度統計</h2><span></span></div><div class="card"><div class="eyebrow">總 Coaching 時數</div><div class="row" style="align-items:end"><div><span id="statsHours" class="big">0</span> / 100 小時</div><b id="statsPct">0%</b></div><div class="progress"><span id="bar"></span></div><p id="statsRemain" class="small" style="margin-top:10px"></p></div><div class="card"><div class="eyebrow">付費／交換時數</div><div class="row" style="align-items:end"><div><span id="statsPaid" class="big">0</span> / 75 小時</div><b id="statsPaidPct">0%</b></div><div class="progress"><span id="statsPaidBar"></span></div><p id="statsPaidRemain" class="small" style="margin-top:10px"></p><div class="v4metrics"><div><span>免費時數</span><b id="statsFree">0 小時</b></div><div><span>已記錄 Coaching 節數</span><b id="statsSessions">0</b></div><div><span>Coachee 人數</span><b id="statsPeople">0</b></div><div><span>已補錄過往時數</span><b id="statsBackfilled">0 小時</b></div></div></div><div class="card"><h3>資料備份</h3><p class="small" style="margin-top:7px">資料只儲存在這部裝置。建議定期匯出備份；PIN 不會包含在備份內。</p><div class="actions"><button class="btn secondary" onclick="exportData()">匯出備份</button><button class="btn secondary" onclick="document.getElementById('importer').click()">匯入備份</button></div><input id="importer" class="hidden" type="file" accept=".json" onchange="importData(event)"></div>`;
  let settings=$('settings');if(settings)settings.innerHTML=`<div class="head"><span></span><h2>設定</h2><span></span></div><div class="card"><label>你的名稱</label><input id="settingsName" type="text" maxlength="30"><label>開始使用 App 時已完成總時數</label><input id="settingsStart" type="number" inputmode="decimal" min="0" step="0.25"><label>其中付費／交換時數</label><input id="settingsStartPaid" type="number" inputmode="decimal" min="0" step="0.25"><small class="v4hint">補錄過往紀錄只補資料，不會再次增加時數。</small><button class="btn primary" style="margin-top:14px" onclick="saveSettings()">儲存設定</button></div><div class="support">🔐 每位使用者的資料只會儲存在自己的裝置，不會因為共用同一條網址而互相看到。</div><button class="btn secondary" style="width:100%" onclick="lockNow()">立即鎖定 App</button>`;
  let c=$('completeForm');if(c){let submit=c.querySelector('button[type=submit]');if(submit)submit.textContent='完成紀錄並加入時數';let pay=$('payment');if(pay&&!pay.nextElementSibling?.classList?.contains('v4hint'))pay.insertAdjacentHTML('afterend','<small class="v4hint">除了「免費／義務」，其他選項都會計入付費／交換時數。</small>')}
  let nav=document.querySelector('.tab[data-s="records"]');if(nav)nav.lastChild.textContent='紀錄';
}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.dataset.s===id));if(id==='records')recordsList();if(id==='stats')stats();if(id==='settings')fillSettings();window.scrollTo({top:0,behavior:'smooth'})}
function newAppointment(){$('apptForm').reset();$('expect').value='60';setMode('online');show('appointment')}
function newBackfill(){$('backfillForm').reset();$('bfActual').value='60';$('bfPayment').value='互 Coach 交換';show('backfill')}
function setMode(v){mode=v;$('online').classList.toggle('sel',v==='online');$('offline').classList.toggle('sel',v==='offline');$('onlineField').classList.toggle('hidden',v!=='online');$('offlineField').classList.toggle('hidden',v!=='offline')}
function setRec(v,b){rec=v;document.querySelectorAll('#recSeg button').forEach(x=>x.classList.remove('sel'));b.classList.add('sel');$('consent').value=v==='沒有'?'不適用':'是'}
function openComplete(id){current=id;let a=state.items.find(x=>x.id===id);if(!a)return;$('completeForm').reset();$('actual').value=a.expect||60;rec='沒有';document.querySelectorAll('#recSeg button').forEach((x,i)=>x.classList.toggle('sel',i===2));$('consent').value='不適用';$('person').innerHTML=`💜 <b>${esc(a.name)}</b>${a.job?' · '+esc(a.job):''}<br>${fmt(a.date)} ${esc(a.time||'')}`;show('complete')}
$('apptForm').onsubmit=e=>{e.preventDefault();let a={id:Date.now().toString(),status:'upcoming',name:$('name').value.trim(),phone:$('phone').value.trim(),job:$('job').value.trim(),date:$('date').value,time:$('time').value,expect:+$('expect').value,mode,link:$('link').value.trim(),place:$('place').value.trim(),plan:$('plan').value.trim()};state.items.unshift(a);last=a.id;save();$('savedInfo').innerHTML=`<b>${esc(a.name)}</b> · ${esc(a.job)}<br>${fmt(a.date)} ${esc(a.time)} · ${a.mode==='online'?'線上':'面對面'}`;show('saved')};
$('completeForm').onsubmit=e=>{e.preventDefault();let a=state.items.find(x=>x.id===current);if(!a)return;Object.assign(a,{status:'done',countMode:'new',actual:+$('actual').value,topic:$('topic').value.trim(),rec,consent:$('consent').value,feedback:$('feedback').value.trim(),reflection:$('reflection').value.trim(),payment:$('payment').value,paynote:$('paynote').value.trim()});save();$('finishMsg').innerHTML=`本節已加入 <b>${num(hrs(a.actual))} 小時</b>。<br>目前總時數 <b>${num(total())}/100</b>；付費／交換時數 <b>${num(paidTotal())}/75</b>。💜`;show('finish')};
$('backfillForm').onsubmit=e=>{e.preventDefault();let a={id:Date.now().toString(),status:'done',countMode:'included',name:$('bfName').value.trim(),job:$('bfJob').value.trim(),phone:$('bfPhone').value.trim(),date:$('bfDate').value,time:$('bfTime').value,actual:+$('bfActual').value,mode:$('bfMode').value,place:$('bfPlace').value.trim(),topic:$('bfTopic').value.trim(),rec:$('bfRec').value,consent:$('bfConsent').value,feedback:$('bfFeedback').value.trim(),reflection:$('bfReflection').value.trim(),payment:$('bfPayment').value,paynote:$('bfPaynote').value.trim()};state.items.unshift(a);save();$('finishMsg').innerHTML=`已補錄 <b>${esc(a.name)}</b> 的 ${num(hrs(a.actual))} 小時 Coaching 資料。<br><b>總時數沒有增加</b>，避免重複計算。`;show('finish')};
function render(){let u=(localStorage.getItem(USER)||'').trim(),t=total(),p=paidTotal(),f=freeTotal(),tp=Math.min(100,Math.round(t)),pp=Math.min(100,Math.round(p/PAID_TARGET*100)),tr=Math.max(0,TARGET-t),pr=Math.max(0,PAID_TARGET-p),up=state.items.filter(x=>x.status==='upcoming');$('welcomeName').textContent=u?`Hi ${u} 👋`:'Hi 👋';$('doneHours').textContent=num(t);$('remain').textContent=tr?`距離 100 小時還有 ${num(tr)} 小時`:'已達成 100 小時目標 🎉';$('pct').textContent=tp+'%';$('ring').style.setProperty('--pct',tp+'%');$('paidHours').textContent=num(p);$('paidBar').style.width=pp+'%';$('paidPct').textContent=pp+'%';$('paidRemain').textContent=pr?`距離 75 小時還有 ${num(pr)} 小時`:'已達成 75 小時付費／交換目標 🎉';$('freeHours').textContent=num(f);$('doneCount').textContent=done().length;$('upCount').textContent=up.length;$('heroTitle').textContent=t>=100?'100 小時達成！🎉':t>=75?'進入最後直路，繼續前進。':t>=50?'已經走過一半，繼續累積。':t>=25?'你已建立自己的節奏。':'一步一步，把經驗累積起來。';let q=['今天不用完成所有剩餘時數，<strong>專注下一節 Coaching 就好。</strong>','每一次專注聆聽，都在累積你作為 Coach 的能力。🌱','一節一節累積，100 小時會由目標慢慢變成紀錄。💜','持續練習，<strong>你正在一步一步靠近 ACC。</strong>'];$('motivation').innerHTML='💜 '+q[new Date().getDate()%q.length];$('homeList').innerHTML=up.length?up.slice(0,3).map(a=>`<div class="item" onclick="openComplete('${a.id}')"><div class="row"><div><h4>${esc(a.name)}</h4><div class="meta">${fmt(a.date)} · ${esc(a.time)}<br>${esc(a.job||'未填寫職業')}</div></div><span class="badge">待完成</span></div></div>`).join(''):'<div class="empty">暫時未有即將進行的預約。<br>可以先安排下一節 Coaching 🌱</div>';stats();fillSettings()}
function setTab(v){tab=v;$('upTab').classList.toggle('sel',v==='upcoming');$('doneTab').classList.toggle('sel',v==='done');recordsList()}
function recordsList(){let arr=state.items.filter(x=>tab==='upcoming'?x.status==='upcoming':x.status==='done');$('recordList').innerHTML=arr.length?arr.map(a=>{let past=a.countMode==='included';return `<div class="item"><div class="row"><div><h4>${esc(a.name)}</h4><div class="meta">${fmt(a.date)}${a.time?' · '+esc(a.time):''}<br>${esc(a.job||'未填寫職業')}${a.status==='done'?`<br>${num(hrs(a.actual))} 小時 · ${esc(a.payment||'未分類')}`:''}</div></div><span class="badge ${past?'v4past':''}">${a.status==='upcoming'?'待完成':past?'過往補錄':'已完成'}</span></div>${a.status==='upcoming'?`<button class="btn primary" style="margin-top:11px" onclick="openComplete('${a.id}')">完成後補紀錄</button>`:`${a.feedback?'<span class="pill">有 Feedback</span>':''}${a.reflection?'<span class="pill">有反思</span>':''}${past?'<span class="pill">不重複加時數</span>':''}`}</div>`}).join(''):`<div class="empty">${tab==='upcoming'?'暫時未有即將進行的預約。':'已完成及補錄的 Coaching 會顯示在這裡。'}</div>`}
function stats(){let t=total(),p=paidTotal(),tp=Math.min(100,Math.round(t)),pp=Math.min(100,Math.round(p/75*100)),tr=Math.max(0,100-t),pr=Math.max(0,75-p);$('statsHours').textContent=num(t);$('statsPct').textContent=tp+'%';$('bar').style.width=tp+'%';$('statsRemain').textContent=tr?`距離 100 小時目標還有 ${num(tr)} 小時。`:'已達成 100 小時目標。';$('statsPaid').textContent=num(p);$('statsPaidPct').textContent=pp+'%';$('statsPaidBar').style.width=pp+'%';$('statsPaidRemain').textContent=pr?`距離 75 小時付費／交換目標還有 ${num(pr)} 小時。`:'已達成 75 小時付費／交換目標。';$('statsFree').textContent=num(freeTotal())+' 小時';$('statsSessions').textContent=done().length;$('statsPeople').textContent=new Set(done().map(x=>(x.name||'').trim().toLowerCase()).filter(Boolean)).size;$('statsBackfilled').textContent=num(backfilled())+' 小時'}
function fillSettings(){let u=(localStorage.getItem(USER)||'').trim();if($('settingsName'))$('settingsName').value=u;if($('settingsStart'))$('settingsStart').value=num(state.startingHours);if($('settingsStartPaid'))$('settingsStartPaid').value=num(state.startingPaidHours)}
function saveSettings(){let n=$('settingsName').value.trim(),s=+$('settingsStart').value,p=+$('settingsStartPaid').value;if(!n)return toast('請輸入你的名稱');if(s<0||p<0||!Number.isFinite(s)||!Number.isFinite(p))return toast('請輸入有效時數');if(p>s)return toast('付費／交換時數不可多於總時數');localStorage.setItem(USER,n);state.startingHours=round(s);state.startingPaidHours=round(p);localStorage.setItem(ONBOARD,'1');save();toast('設定已儲存 💜')}
function exportData(){let data={version:3,user:(localStorage.getItem(USER)||'').trim(),state},u=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='coaching-journey-backup.json';a.click();URL.revokeObjectURL(u)}
function importData(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let o=JSON.parse(r.result),s=o.state||o;if(!Array.isArray(s.items))throw 0;state={...fresh(),...s,target:100,paidTarget:75};if(o.user)localStorage.setItem(USER,o.user);localStorage.setItem(ONBOARD,'1');save();toast('備份已匯入')}catch(_){toast('備份檔格式不正確')}};r.readAsText(f)}
function calendar(){let a=state.items.find(x=>x.id===last);if(!a)return;let start=new Date(`${a.date}T${a.time}:00`),end=new Date(start.getTime()+a.expect*60000),f=d=>d.getFullYear()+String(d.getMonth()+1).padStart(2,'0')+String(d.getDate()).padStart(2,'0')+'T'+String(d.getHours()).padStart(2,'0')+String(d.getMinutes()).padStart(2,'0')+'00',lines=['BEGIN:VCALENDAR','VERSION:2.0','BEGIN:VEVENT',`UID:${a.id}@coach`,`DTSTART:${f(start)}`,`DTEND:${f(end)}`,`SUMMARY:Coaching｜${a.name}`,'END:VEVENT','END:VCALENDAR'],u=URL.createObjectURL(new Blob([lines.join(String.fromCharCode(13,10))],{type:'text/calendar'})),l=document.createElement('a');l.href=u;l.download=`Coaching-${a.name}-${a.date}.ics`;l.click();URL.revokeObjectURL(u)}
function hex(b){return[...b].map(x=>x.toString(16).padStart(2,'0')).join('')}async function hash(pin,salt){let d=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(salt+':'+pin));return hex(new Uint8Array(d))}function pinRec(){try{return JSON.parse(localStorage.getItem(PIN)||'null')}catch{return null}}function salt(){let a=new Uint8Array(16);crypto.getRandomValues(a);return hex(a)}
function togglePinVisibility(){let i=$('pin'),b=$('pinEye'),show=i.type==='password';i.type=show?'text':'password';b.textContent=show?'🙈':'👁️'}
function prepareLock(){if(sessionStorage.getItem('coach_unlocked')==='1')return $('lock').classList.add('hidden');let r=pinRec(),setup=localStorage.getItem(ONBOARD)==='1',u=(localStorage.getItem(USER)||'').trim();$('lock').classList.remove('hidden');$('pin').value='';$('pinError').textContent='';if(!setup){$('nameField').classList.remove('hidden');$('progressSetup').classList.remove('hidden');$('userName').value=u;$('startHours').value=num(state.startingHours);$('startPaid').value=num(state.startingPaidHours);$('pinTitle').textContent='設定你的 Coaching Journey';$('pinHelp').textContent=r?'先確認目前進度，再輸入原有 PIN 完成升級。':'輸入名稱、目前進度，再設定 4–6 位數字 PIN。';$('pinBtn').textContent=r?'儲存進度並解鎖':'設定並開始'}else{$('nameField').classList.add('hidden');$('progressSetup').classList.add('hidden');$('pinTitle').textContent=u?`歡迎回來，${u}`:'歡迎回來';$('pinHelp').textContent='輸入你的私人 PIN 解鎖。';$('pinBtn').textContent='解鎖'}}
async function handlePin(){let v=$('pin').value.trim(),r=pinRec(),setup=localStorage.getItem(ONBOARD)==='1';$('pinError').textContent='';if(!/^\d{4,6}$/.test(v))return $('pinError').textContent='請輸入 4–6 位數字 PIN';if(!setup){let n=$('userName').value.trim(),s=+$('startHours').value,p=+$('startPaid').value;if(!n)return $('pinError').textContent='請先輸入你的名稱';if(!Number.isFinite(s)||s<0)return $('pinError').textContent='請輸入目前已完成總時數';if(!Number.isFinite(p)||p<0)return $('pinError').textContent='請輸入付費／交換時數';if(p>s)return $('pinError').textContent='付費／交換時數不可多於總時數';if(r&&await hash(v,r.salt)!==r.hash)return $('pinError').textContent='PIN 不正確，請再試一次';if(!r){let sl=salt();localStorage.setItem(PIN,JSON.stringify({salt:sl,hash:await hash(v,sl)}))}localStorage.setItem(USER,n);state.startingHours=round(s);state.startingPaidHours=round(p);localStorage.setItem(ONBOARD,'1');save();sessionStorage.setItem('coach_unlocked','1');$('lock').classList.add('hidden');return toast('設定完成 💜')}if(r&&await hash(v,r.salt)===r.hash){sessionStorage.setItem('coach_unlocked','1');$('lock').classList.add('hidden');render()}else $('pinError').textContent='PIN 不正確，請再試一次'}
function lockNow(){sessionStorage.removeItem('coach_unlocked');prepareLock()}
buildUI();
Object.assign(window,{show,newAppointment,newBackfill,setMode,setRec,openComplete,setTab,saveSettings,exportData,importData,calendar,togglePinVisibility,handlePin,lockNow});
$('pin').addEventListener('keydown',e=>{if(e.key==='Enter')handlePin()});render();prepareLock();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js',{updateViaCache:'none'}).then(r=>r.update()).catch(()=>{});
})();