(()=>{
'use strict';
const LANG_KEY='coaching_lang_v1';
const EN={'主頁':'Home','紀錄':'Records','統計':'Progress','設定':'Settings','新增 Coaching 預約':'Add Coaching Appointment','補錄過往 Coaching 紀錄':'Add Past Coaching Record','補錄過往 Coaching':'Add Past Coaching','完成 Coaching 紀錄':'Complete Coaching Record','即將進行':'Upcoming','已完成':'Completed','過往補錄':'Past Records','查看全部':'View all','儲存預約':'Save Appointment','修改預約':'Edit Appointment','取消預約':'Cancel Appointment','取消這個預約':'Cancel this appointment','查看我的預約':'View my appointments','加入 Apple 日曆':'Add to Apple Calendar','分享預約訊息':'Share booking message','複製預約訊息':'Copy booking message','預約訊息預覽':'Booking message preview','預約已儲存！':'Appointment saved!','資料備份':'Data Backup','匯出備份':'Export Backup','匯入備份':'Import Backup','鎖定 App':'Lock App','儲存設定':'Save Settings','你的名稱':'Your name','開始使用 App 前的進度':'Progress before using the app','目前已完成 Coaching 總時數':'Current total Coaching hours','其中付費／交換時數':'Paid / exchange hours within total','私人 PIN':'Private PIN','設定並開始':'Set up & start','日期':'Date','開始時間':'Start time','預計時長':'Expected duration','進行方式':'Format','線上':'Online','面對面':'In person','線上連結':'Online link','面對面地點':'Meeting location','預計 Coaching 主題（選填）':'Expected Coaching topic (optional)','Coachee 姓名':'Coachee name','聯絡電話':'Contact phone','身份／職業':'Role / occupation','Coachee 基本資料':'Coachee details','預約安排':'Appointment','談話準備':'Session preparation','實際 Coaching 時長':'Actual Coaching duration','本節 Coaching 主題':'Coaching topic','時數類別':'Hour category','付費／交換':'Paid / exchange','免費':'Free','付費／交換方式':'Payment / exchange method','備註（選填）':'Notes (optional)','錄音與同意':'Recording & consent','錄音／錄影':'Audio / video recording','有錄音':'Audio','有錄影':'Video','沒有':'None','不適用':'Not applicable','是':'Yes','否':'No','Feedback 與反思':'Feedback & reflection','Coachee 的 Feedback':'Coachee feedback','你的個人反思':'Your reflection','完成並計入時數':'Complete & count hours','過往 Coachee':'Past Coachee','過往 Coaching 資料':'Past Coaching details','開始時間（選填）':'Start time (optional)','地點／會議連結（選填）':'Location / meeting link (optional)','Coaching 主題':'Coaching topic','當時的時數類別':'Hour category at the time','總 Coaching 時數':'Total Coaching hours','付費／交換時數':'Paid / exchange hours','免費時數':'Free hours','已記錄 Coachee':'Recorded Coachees','ICF ACC 旅程':'ICF ACC Journey','每一節，都讓你更接近目標。':'Every session brings you closer to your goal.'};
const PLACEHOLDERS={'例如：Carrie':'e.g. Carrie','例如：15':'e.g. 15','例如：10':'e.g. 10','例如：工程師、藝人、公司老闆':'e.g. Engineer, founder, manager','Zoom / Meet / Teams':'Zoom / Meet / Teams','可以先記下對方想探索的方向':'Note what they may want to explore','例如：工程師、創業者、HR':'e.g. Engineer, founder, HR','例如：Zoom／中環咖啡店':'e.g. Zoom / Central café','例如：互 Coach 1 小時；咖啡 HK$45':'e.g. 1-hour peer coaching exchange','可以貼上對方的文字 Feedback':'Paste the Coachee’s feedback here','這次做得好的是？下次想改善什麼？我學到什麼？':'What went well? What would I improve next time? What did I learn?'};
function lang(){return localStorage.getItem(LANG_KEY)||'zh'}
function setLang(v){localStorage.setItem(LANG_KEY,v);if(v==='zh'&&document.body.dataset.v23Translated==='1'){location.reload();return}applyLang();renderLangControls()}
function translateTextNode(n){if(lang()!=='en')return;const raw=n.nodeValue,trim=raw.trim();if(!trim)return;if(EN[trim])n.nodeValue=raw.replace(trim,EN[trim])}
function applyLang(){const isEn=lang()==='en';document.documentElement.lang=isEn?'en':'zh-Hant';if(!isEn)return;document.body.dataset.v23Translated='1';const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT),nodes=[];while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(translateTextNode);document.querySelectorAll('input[placeholder],textarea[placeholder]').forEach(el=>{const p=el.getAttribute('placeholder');if(PLACEHOLDERS[p])el.setAttribute('placeholder',PLACEHOLDERS[p])});const title=document.querySelector('#pinTitle');if(title&&title.textContent.includes('開始你的'))title.textContent='Start your ACC Coaching Journey';const help=document.querySelector('#pinHelp');if(help&&help.textContent.includes('第一次使用'))help.textContent='First time here? Set up your personal progress to begin.'}
function langControl(){const d=document.createElement('div');d.className='v23LangSeg';d.innerHTML='<button type="button" data-lang="zh">繁中</button><button type="button" data-lang="en">EN</button>';d.onclick=e=>{const b=e.target.closest('button[data-lang]');if(b)setLang(b.dataset.lang)};return d}
function renderLangControls(){document.querySelectorAll('.v23LangSeg button').forEach(b=>b.classList.toggle('on',b.dataset.lang===lang()))}
function installLang(){const lockTop=document.querySelector('.lockTop');if(lockTop&&!document.querySelector('.v23LockLang')){const wrap=document.createElement('div');wrap.className='v23LockLang';wrap.appendChild(langControl());lockTop.after(wrap)}const settings=document.querySelector('#settings');if(settings&&!document.querySelector('#v23LangCard')){const card=document.createElement('div');card.id='v23LangCard';card.className='card';card.innerHTML='<div class="v23LangRow"><div><b>語言 / Language</b><div class="small" style="margin-top:4px">繁體中文 / English</div></div></div>';card.querySelector('.v23LangRow').appendChild(langControl());const first=settings.querySelector('.card');if(first)settings.insertBefore(card,first);else settings.appendChild(card)}renderLangControls()}
function brand(){document.querySelectorAll('.mark,.lockMark').forEach(el=>{if(el.querySelector('img'))return;el.textContent='';const im=document.createElement('img');im.src='icon-192.png';im.className='v23BrandIcon';im.alt='';el.appendChild(im)})}
function animateScreen(id){const s=document.getElementById(id);if(!s)return;s.classList.remove('v23-enter');void s.offsetWidth;s.classList.add('v23-enter');s.querySelectorAll('.hero,.goalCard,.quote,.stat,.item,.card').forEach((el,i)=>{el.classList.remove('v23-stagger');el.style.animationDelay=Math.min(i,5)*35+'ms';void el.offsetWidth;el.classList.add('v23-stagger')})}
function celebrate(){const card=document.querySelector('#saved .card');if(!card)return;const icon=card.firstElementChild;if(icon){icon.classList.remove('v23-pop');void icon.offsetWidth;icon.classList.add('v23-pop')}if(card.querySelector('.v23-spark'))return;['✦','✧','✦'].forEach((t,i)=>{const s=document.createElement('span');s.className='v23-spark';s.textContent=t;s.style.left=(40+i*10)+'%';s.style.top=(48+(i%2)*8)+'px';s.style.animationDelay=(i*70)+'ms';card.style.position='relative';card.appendChild(s);setTimeout(()=>s.remove(),1000)})}
const originalShow=window.show;if(typeof originalShow==='function'){window.show=function(id){const r=originalShow.apply(this,arguments);requestAnimationFrame(()=>{installLang();brand();applyLang();animateScreen(id);if(id==='saved')celebrate()});return r}}
installLang();brand();applyLang();const active=document.querySelector('.screen.active');if(active)animateScreen(active.id);
})();
